---
- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Start Logstash
  service:
    name: logstash
    state: started
    enabled: yes

- name: Start Kibana
  service:
    name: kibana
    state: started
    enabled: yes

- name: Restart Kibana
  service:
    name: kibana
    state: restarted

